---
title: Eccentric Devzone
timezone: UTC
collections:
  charter-chars:
    title: Charter-Characters
    output: false
  ec-arcs:
    title: EC-Arcs
    output: true
  ec-images:
    title: EC-Images
    output: false
  ec-items:
    title: EC-Items
    output: false
  ec-relationships:
    title: EC-Relationships
    output: false
  posts:
    title: Posts
    output: true
  ss-arcs:
    title: SS-Arcs
    output: true
  ss-images:
    title: SS-Images
    output: false
  ss-items:
    title: SS-Items
    output: false
  ss-relationships:
    title: SS-Relationships
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: ec-arcs
  values:
    primary-image: 
    background-image: 
    gradient-top-color: 
    gradient-bottom-color: 
- scope:
    path: ''
    type: ec-images
  values:
    primary-image: 
- scope:
    path: ''
    type: ec-items
  values:
    primary-image: 
    sfx-hover-file: "/temp_pluk.mp3"
    sfx-click-file: "/temp_bwomm.mp3"
- scope:
    path: ''
    type: ec-relationships
  values:
    relationship: 
    primary-image: 
- scope:
    path: ''
    type: ss-arcs
  values:
    primary-image: 
    background-image: 
    gradient-top-color: 
    gradient-bottom-color: 
- scope:
    path: ''
    type: ss-images
  values:
    primary-image: 
- scope:
    path: ''
    type: ss-items
  values:
    primary-image: 
    sfx-hover-file: 
    sfx-click-file: 
- scope:
    path: ''
    type: ss-relationships
  values:
    relationship: 
    primary-image: 
- scope:
    path: ''
    type: charter-chars
  values:
    subtitle: 
    char-image: 
description: 
url: "."
repository: crekulon/ec-profiles
Is-SFX-Enabled: false
Select-Music-File: "./pyre_life_sentence.mp3"
Select-Music-Credit: Darren Korb - Life Sentence
EC-Subtitle: yea of burning heart
EC-Music-File: "/martyrs_blood.mp3"
EC-Music-Credit: Corey Vitalis - Martyrs Blood
EC-SFX-Portrait-Hover-File: 
EC-SFX-Portrait-Click-File: 
EC-SFX-Button-Hover-File: 
EC-SFX-Button-Click-File: 
SS-Subtitle: yea of churning mind
SS-SFX-Portrait-Hover-File: 
SS-SFX-Portrait-Click-File: 
SS-SFX-Button-Hover-File: 
SS-SFX-Button-Click-File: 
SS-Music-File: "/severance.mp3"
SS-Music-Credit: Joel Louviere / Sokkycakes - Severance
Is-Charter-Active: true
Charter-Trigger-Text: Stranger Campaigns
Charter-Title: Highly WIP!
Charter-Description: Hey there, glad you clicked! Right now, this portion of the site
  is HEAVILY WIP, so try not to pay attention to it.
Charter-Banner: "/uploads/ivdiz.png"
Charter-Join-Embed: <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeDVKpY5XuEE2KM1Hk9zoqC3WbuY_qQtyzYlJG-GMMMKWtNSg/viewform?embedded=true"
  width="640" height="780" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
Charter-SFX-Hover-File: 
Charter-SFX-Click-File: 
Charter-Music-File: "/uploads/Team%20Fortress%202%20Soundtrack%20Upgrade%20Station.mp3"
Charter-Music-Credit: Mike Morasky - Upgrade Station
