---
title: Eccentric Devzone
timezone: UTC
collections:
  charter-chars:
    title: Charter-Characters
    output: false
  ec-arcs:
    title: EC-Arcs
    output: true
  ec-images:
    title: EC-Images
    output: false
  ec-items:
    title: EC-Items
    output: false
  ec-relationships:
    title: EC-Relationships
    output: false
  posts:
    title: Posts
    output: true
  ss-arcs:
    title: SS-Arcs
    output: true
  ss-images:
    title: SS-Images
    output: false
  ss-items:
    title: SS-Items
    output: false
  ss-relationships:
    title: SS-Relationships
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: ec-arcs
  values:
    primary-image: 
    background-image: 
    gradient-top-color: 
    gradient-bottom-color: 
- scope:
    path: ''
    type: ec-images
  values:
    primary-image: 
- scope:
    path: ''
    type: ec-items
  values:
    primary-image: 
    sfx-hover-file: "/temp_pluk.mp3"
    sfx-click-file: "/temp_bwomm.mp3"
- scope:
    path: ''
    type: ec-relationships
  values:
    relationship: 
    primary-image: 
- scope:
    path: ''
    type: ss-arcs
  values:
    primary-image: 
    background-image: 
    gradient-top-color: 
    gradient-bottom-color: 
- scope:
    path: ''
    type: ss-images
  values:
    primary-image: 
- scope:
    path: ''
    type: ss-items
  values:
    primary-image: 
    sfx-hover-file: 
    sfx-click-file: 
- scope:
    path: ''
    type: ss-relationships
  values:
    relationship: 
    primary-image: 
- scope:
    path: ''
    type: charter-chars
  values:
    subtitle: 
    char-image: 
description: 
url: "."
repository: crekulon/ec-profiles
Is-SFX-Enabled: false
EC-Subtitle: yea of burning heart
EC-Music-File: "/martyrs_blood.mp3"
EC-Music-Credit: Corey Vitalis - Martyrs Blood
EC-SFX-Portrait-Hover-File: 
EC-SFX-Portrait-Click-File: 
EC-SFX-Button-Hover-File: 
EC-SFX-Button-Click-File: 
SS-Subtitle: yea of churning mind
SS-SFX-Portrait-Hover-File: 
SS-SFX-Portrait-Click-File: 
SS-SFX-Button-Hover-File: 
SS-SFX-Button-Click-File: 
SS-Music-File: "/severance.mp3"
SS-Music-Credit: Joel Louviere / Sokkycakes - Severance
Is-Charter-Active: false
Charter-Trigger-Text: Da Charta
Charter-Title: yea of froggening mind
Charter-Description: |-
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis et sapien porttitor, facilisis augue non, hendrerit lectus. Morbi non turpis sit amet est aliquet efficitur. Etiam a malesuada purus. Cras et ullamcorper elit, eget finibus velit. Aenean consequat, magna ac aliquet tincidunt, quam sapien tempor lorem, eget scelerisque leo ante a nulla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed bibendum molestie velit, in lobortis diam dapibus eu. Pellentesque egestas eu erat eu gravida.
  Nunc pulvinar nec odio eget ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae porttitor nibh. Vestibulum sed lacus rutrum, ornare mauris et, blandit erat. Morbi eleifend molestie eros, vel laoreet libero auctor sit amet. Duis sit amet laoreet turpis. Sed ut turpis porttitor, porta sapien sed, tempus eros. Integer rutrum laoreet lorem, a pulvinar arcu. Suspendisse sodales placerat dui non porta. Integer congue scelerisque nulla, at pellentesque ex consectetur sed. Vestibulum odio sapien, tincidunt ac commodo at, dictum laoreet sem. Nullam sit amet condimentum neque, sit amet porta nunc. Aenean dui nibh, consequat a lacus ac, blandit eleifend tellus. Duis efficitur, tortor eget bibendum pretium, diam libero molestie arcu, vitae volutpat mi dui eu urna. Donec placerat arcu at gravida imperdiet. Nunc dignissim rhoncus felis ut vulputate.
Charter-Banner: "/uploads/2020-12-20_02-07-41-126_Talim%20-%20Simplicity.png"
Charter-Join-Embed: <iframe src="https://docs.google.com/forms/d/e/1FAIpQLScv2roVSiXaLGEMskr_lxE2l9rlC9PevgH3tmB-aRIORl4UHg/viewform?embedded=true"
  width="640" height="816" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
Charter-SFX-Hover-File: 
Charter-SFX-Click-File: 
Charter-Music-File: "/martyrs_blood.mp3"
Charter-Music-Credit: Corey Vitalis - Martyrs Blood
